#!/bin/bash
python3 datasetGenerating.py ../source_videos/bowl2_alex.mp4 bowl True
python3 datasetGenerating.py ../source_videos/bowl1_alex.mp4 bowl True
python3 datasetGenerating.py ../source_videos/pottedplant2_alex pottedplant True
python3 datasetGenerating.py ../source_videos/vase_alex vase True
python3 datasetGenerating.py ../source_videos/banana1_alex.mp4 banana True
python3 datasetGenerating.py ../source_videos/fork2_alex fork True
python3 datasetGenerating.py ../source_videos/fork1_alex.mp4 fork True
python3 datasetGenerating.py ../source_videos/tv2_alex.mp4 tvmonitor True
python3 datasetGenerating.py ../source_videos/tv1_alex.mp4 tvmonitor True
python3 datasetGenerating.py ../source_videos/remote_alex.mp4 remote True
python3 datasetGenerating.py ../source_videos/refrigerator_alex.mp4 refrigerator True
python3 datasetGenerating.py ../source_videos/microwave_alex.mp4 microwave True
python3 datasetGenerating.py ../source_videos/chair3_alex.mp4 chair True
python3 datasetGenerating.py ../source_videos/chair2_alex.mp4 chair True
python3 datasetGenerating.py ../source_videos/chair1_alex.mp4 chair True
python3 datasetGenerating.py ../source_videos/toilet-gus.mp4 toilet True
python3 datasetGenerating.py ../source_videos/table-gus.mp4 table True
python3 datasetGenerating.py ../source_videos/sofa-gus.mp4 sofa True
python3 datasetGenerating.py ../source_videos/sink-gus.mp4 sink True
python3 datasetGenerating.py ../source_videos/Microwave-gus.mp4 microwave True
python3 datasetGenerating.py ../source_videos/laptop-gus.mp4 laptop True
python3 datasetGenerating.py ../source_videos/knife-gus.mp4 knife True
python3 datasetGenerating.py ../source_videos/Fridge-gus.mp4 refrigerator True
python3 datasetGenerating.py ../source_videos/fork-gus.mp4 fork True
python3 datasetGenerating.py ../source_videos/Cup-gus.mp4 glass True
python3 datasetGenerating.py ../source_videos/clock-gus.mp4 clock True
python3 datasetGenerating.py ../source_videos/bowl-gus.mp4 bowl True
python3 datasetGenerating.py ../source_videos/bottle-gus.mp4 bottle True
python3 datasetGenerating.py ../source_videos/Backpack-gus.mp4 backpack True
python3 datasetGenerating.py ../source_videos/ant_cat.mp4 cat True
python3 datasetGenerating.py ../source_videos/ant_book.mp4 book True
python3 datasetGenerating.py ../source_videos/ant_plant.mp4 pottedplant True
python3 datasetGenerating.py ../source_videos/ant_laptop.mp4 laptop True
python3 datasetGenerating.py ../source_videos/tv_ant1.mp4 tvmonitor True
python3 datasetGenerating.py ../source_videos/tv_ant.mp4 tvmonitor True
python3 datasetGenerating.py ../source_videos/book_ant.mp4 book True
python3 datasetGenerating.py ../source_videos/remote_ant.mp4 remote True
python3 datasetGenerating.py ../source_videos/book_ant1.mp4 book True
python3 datasetGenerating.py ../source_videos/tv_ant2.mp4 tvmonitor True
python3 datasetGenerating.py ../source_videos/bottle_ant.mp4 bottle True
echo "Finished"
